#!/bin/bash

if [ -z $1 ]; then

  echo -e "\e[31mERROR:\e[0m The argument is missing!"
  echo -e "\e[32mINFOR:\e[0m It should be BESIII, Belle_II, or Example."
  echo -e "\e[32mINFOR:\e[0m If you want to employ the program for the BESIII experiment, please execute: ./Configure BESIII"
  echo -e "\e[32mINFOR:\e[0m If you want to employ the program for the Belle II experiment, please execute: ./Configure Belle_II"
  echo -e "\e[32mINFOR:\e[0m If you want to try the program with examples under the directory examples, please execute: ./Configure Example"
  exit 1

elif [ $1 = BESIII ]; then

  cp share/pid_3pchrg_txtpnm_texpnm_iccp.dat_BESIII pid_3pchrg_txtpnm_texpnm_iccp.dat
  cp underlying_topoana.card_BESIII underlying_topoana.card

elif [ $1 = Belle_II ]; then

  cp share/pid_3pchrg_txtpnm_texpnm_iccp.dat_Belle_II pid_3pchrg_txtpnm_texpnm_iccp.dat
  cp underlying_topoana.card_Belle_II underlying_topoana.card

elif [ $1 = Example ]; then

  cp share/pid_3pchrg_txtpnm_texpnm_iccp.dat_Example pid_3pchrg_txtpnm_texpnm_iccp.dat
  cp underlying_topoana.card_Example underlying_topoana.card

else

  echo -e "\e[31mERROR:\e[0m The argument is invaild!"
  echo -e "\e[32mINFOR:\e[0m It should be BESIII, Belle_II, or Example."
  echo -e "\e[32mINFOR:\e[0m If you want to employ the program for the BESIII experiment, please execute: ./Configure BESIII"
  echo -e "\e[32mINFOR:\e[0m If you want to employ the program for the Belle II experiment, please execute: ./Configure Belle_II"
  echo -e "\e[32mINFOR:\e[0m If you want to try the program with examples under the directory examples, please execute: ./Configure Example"
  exit 2

fi

# This script sets the package path automatically.

pkgPath=`pwd`
sed -i 's:m_pkgPath=.*:m_pkgPath=\"'$pkgPath'\/\";:g' include/topoana.h 
sed -i 's:RequirePackage.*ifxetex:RequirePackage{'$pkgPath'/share/ifxetex:g' share/geometry.sty

# The following statements suggest adding the absolute path of the executable to the envionment variable PATH.

echo -e "\e[32;1mHere is a suggestion: in order to execute \"topoana.exe\" without any path, you should add its absolute path to the envionment variable \"PATH\". Upon the shell you are using, you can set this up by following one of the two guidelines below:\e[0m"
echo -e "\e[32;1m1) In case of bash, please copy the following statement and paste it into ~/.bash_profile,\e[0m"
echo -e "\e[32;1m   export PATH=${pkgPath}/bin:\$PATH\e[0m"
echo -e "\e[32;1m2) In case of (t)csh, please copy the following statement and paste it into ~/.(t)cshrc,\e[0m"
echo -e "\e[32;1m   setenv PATH ${pkgPath}/bin:\$PATH\e[0m"

exit 0
