#!/bin/bash

# This following statements set the package path automatically.

pkgPath=`pwd`
if [ ${OSTYPE:0:6} != darwin ]; then
  sed -i 's:m_pkgPath=.*:m_pkgPath=\"'$pkgPath'\/\";:g' include/topoana.h
  sed -i 's:RequirePackage.*ifxetex:RequirePackage{'$pkgPath'/share/ifxetex:g' share/geometry.sty
else
  sed -i "" 's:m_pkgPath=.*:m_pkgPath=\"'$pkgPath'\/\";:g' include/topoana.h
  sed -i "" 's:RequirePackage.*ifxetex:RequirePackage{'$pkgPath'/share/ifxetex:g' share/geometry.sty
fi


# The following statements print the guidelines for adding the absolute path of the executable of the program to the envionment variable PATH.

echo -e "\e[32;1mHere is a suggestion\e[0m: in order to execute \"\e[32;1mtopoana.exe\e[0m\" without any path, you should add its absolute path to the envionment variable \"\e[32;1mPATH\e[0m\". Upon the shell you are using, you can set this up by following one of the two guidelines below:\e[0m"
echo -e "1) In the case of \e[32;1mbash\e[0m, please execute the following statement in the current session, and then copy and paste it into \e[32;1m~/.bash_profile\e[0m,"
echo -e "\e[32;1m   export PATH=${pkgPath}/bin:\$PATH\e[0m"
echo -e "2) In the case of \e[32;1m(t)csh\e[0m, please execute the following statement in the current session, and then copy and paste it into \e[32;1m~/.(t)cshrc\e[0m,"
echo -e "\e[32;1m   setenv PATH ${pkgPath}/bin:\$PATH\e[0m"

exit 0
